apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-spring-boot
  namespace: openshift-gitops
spec:
  destination:
    namespace: spring-boot
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: spring-boot/app
    repoURL: https://github.com/masp2r/argocd-poc.git
    targetRevision: spring-boot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true