apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-app-docker
  namespace: openshift-gitops
spec:
  destination:
    namespace: app-docker
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/masp2r/argocd-poc.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true